
import requests
import json
import re

# East Hampton Tighe & Bond
# GIS: https://hosting.tighebond.com/EastHamptonCT_Public/
# Cards: https://www.propertyrecordcards.com/PropertyResults.aspx?towncode=42&uniqueid={ACCOUNT_NUMBER}

def test_property_record_card_direct():
    print("\n--- Testing Direct PropertyRecordCards Access ---")
    # Using a known ID from research: R00525 (7 MAIN ST)
    account_number = "R00525"
    url = f"https://www.propertyrecordcards.com/PropertyResults.aspx?towncode=42&uniqueid={account_number}"
    
    print(f"Fetching {url}...")
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'
    }
    resp = requests.get(url, headers=headers)
    
    if resp.status_code == 200:
        print("Success! Checking for owner info...")
        if "CASSELLS DEWIGHT R" in resp.text:
            print("Found owner 'CASSELLS DEWIGHT R' in response.")
        else:
            print("Did not find expected owner string.")
            print(resp.text[:500])
    else:
        print(f"Failed: {resp.status_code}")

def test_tighe_bond_discovery():
    print("\n--- Testing Tighe & Bond Discovery (ArcGIS) ---")
    
    # URL for the ArcGIS 'find' service
    # We strip the token to see if it works without it, or if we can find a public one.
    # Base MapServer URL: https://hostingdata3.tighebond.com/arcgis/rest/services/EastHamptonCT/EastHamptonDynamic/MapServer
    
    base_find_url = "https://hostingdata3.tighebond.com/arcgis/rest/services/EastHamptonCT/EastHamptonDynamic/MapServer/find"
    
    params = {
        'searchText': 'Main',
        'contains': 'true',
        'searchFields': 'ParcelPolygon.Parcel_ID,CAMA.Owner,ParcelPolygon.StreetAddr',
        'sr': '',
        'layers': '0', # Probably layer 0 is the parcel layer
        'layerDefs': '',
        'returnGeometry': 'false',
        'f': 'pjson',
        # 'token': '' # Intentionally omitting token first
    }
    
    print("Attempting search WITHOUT token...")
    try:
        resp = requests.get(base_find_url, params=params, headers={'Referer': 'https://hosting.tighebond.com/'})
        data = resp.json()
        
        if 'error' in data:
            print(f"Error without token: {data['error']}")
            
            # If token is required, we need a strategy to get one.
            # Usually these are generated by the 'ExportWebMap' or just embedded in the JS config.
            # But let's try to verify if the 'hostingdata3' server is accessible at all.
        else:
            print("Success WITHOUT token!")
            results = data.get('results', [])
            print(f"Found {len(results)} results.")
            if results:
                print("First result sample:", results[0])
                
    except Exception as e:
        print(f"Request failed: {e}")

    # Fallback: Try with the token captured from browser (it might still be valid for a bit)
    # Token was: psQ939dyvqF6ohB-0djehrwdu2jlV1ZmO3kbxPQTFCXav-SG-K0LTd5Ou7R8nenBktEZ2Drw14Qgu48ti6rVsA..
    print("\nAttempting search WITH stale token (validity check)...")
    params['token'] = 'psQ939dyvqF6ohB-0djehrwdu2jlV1ZmO3kbxPQTFCXav-SG-K0LTd5Ou7R8nenBktEZ2Drw14Qgu48ti6rVsA..'
    try:
        resp = requests.get(base_find_url, params=params, headers={'Referer': 'https://hosting.tighebond.com/'})
        data = resp.json()
        if 'results' in data:
            print(f"Success WITH token! Found {len(data['results'])} results.")
        else:
            print(f"Failed with token: {data.get('error', 'Unknown error')}")
    except Exception as e:
        print(f"Request failed: {e}")

if __name__ == "__main__":
    test_property_record_card_direct()
    test_tighe_bond_discovery()
