
# This file contains the configuration for municipal data sources.
# It is shared between the API and the Updater.

MUNICIPAL_DATA_SOURCES = {
    'ANSONIA': {'type': 'MAPXPRESS', 'domain': 'ansonia.mapxpress.net', 'frequency': 'Monthly'},
    'POMFRET': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/pomfretct/', 'frequency': 'Weekly'},
    'BEACON FALLS': {'type': 'MAPXPRESS', 'domain': 'beaconfalls.mapxpress.net', 'frequency': 'Monthly'},
    'BERLIN': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/berlinct/', 'frequency': 'Nightly'},
    'BETHANY': {'type': 'MAPXPRESS', 'domain': 'bethany.mapxpress.net', 'frequency': 'Monthly'},
    'BETHLEHEM': {'type': 'MAPXPRESS', 'domain': 'bethlehem.mapxpress.net', 'frequency': 'Monthly'},
    'BRIDGEPORT': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/bridgeportct/', 'frequency': 'Nightly'},
    'BRISTOL': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/bristolct/', 'frequency': 'Nightly'},
    'MANSFIELD': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/mansfieldct/', 'frequency': 'Weekly'},
    # Additional Vision Appraisal municipalities with missing photos
    'NORWALK': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/norwalkct/', 'frequency': 'Nightly'},
    'GLASTONBURY': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/glastonburyct/', 'frequency': 'Nightly'},
    'WINDSOR': {'type': 'windsor_api', 'url': 'https://windsorct.com', 'frequency': 'Daily'},
    'WETHERSFIELD': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/wethersfieldct/', 'frequency': 'Weekly'},
    'VERNON': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/vernonct/', 'frequency': 'Weekly'},
    'STONINGTON': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/stoningtonct/', 'frequency': 'Weekly'},
    'BLOOMFIELD': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/bloomfieldct/', 'frequency': 'Weekly'},
    'AVON': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/avonct/', 'frequency': 'Weekly'},
    'WOLCOTT': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/wolcottct/', 'frequency': 'Weekly'},
    'WINDHAM': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/windhamct/', 'frequency': 'Weekly'},
    'WOODSTOCK': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/woodstockct/', 'frequency': 'Weekly'},
    'BROOKFIELD': {'type': 'MAPXPRESS', 'domain': 'brookfield.mapxpress.net'},
    'BURLINGTON': {'type': 'MAPXPRESS', 'domain': 'burlington.mapxpress.net'},
    'CANTON': {'type': 'MAPXPRESS', 'domain': 'canton.mapxpress.net'},
    'CHESHIRE': {'type': 'MAPXPRESS', 'domain': 'cheshire.mapxpress.net'},
    'COLCHESTER': {'type': 'MAPXPRESS', 'domain': 'colchester.mapxpress.net'},
    'COVENTRY': {'type': 'MAPXPRESS', 'domain': 'coventry.mapxpress.net'},
    'DERBY': {'type': 'MAPXPRESS', 'domain': 'derby.mapxpress.net'},
    'EAST HAVEN': {'type': 'MAPXPRESS', 'domain': 'easthaven.mapxpress.net'},
    'FARMINGTON': {'type': 'MAPXPRESS', 'domain': 'farmington.mapxpress.net'},
    'LITCHFIELD': {'type': 'MAPXPRESS', 'domain': 'litchfield.mapxpress.net'},
    'MIDDLEBURY': {'type': 'MAPXPRESS', 'domain': 'middlebury.mapxpress.net'},
    'NAUGATUCK': {'type': 'MAPXPRESS', 'domain': 'naugatuck.mapxpress.net'},
    'NEW BRITAIN': {'type': 'MAPXPRESS', 'domain': 'newbritain.mapxpress.net', 'id_param': 'parid'},
    'NEWTOWN': {'type': 'MAPXPRESS', 'domain': 'newtown.mapxpress.net'},
    'OXFORD': {'type': 'MAPXPRESS', 'domain': 'oxford.mapxpress.net'},
    'PLAINVILLE': {'type': 'MAPXPRESS', 'domain': 'plainville.mapxpress.net'},
    'SALEM': {'type': 'MAPXPRESS', 'domain': 'salem.mapxpress.net'},
    'SEYMOUR': {'type': 'MAPXPRESS', 'domain': 'seymour.mapxpress.net'},
    'SOUTHBURY': {'type': 'MAPXPRESS', 'domain': 'southbury.mapxpress.net'},
    'SUFFIELD': {'type': 'MAPXPRESS', 'domain': 'suffield.mapxpress.net'},
    'WEST HAVEN': {'type': 'MAPXPRESS', 'domain': 'westhaven.mapxpress.net'},
    # PropertyRecordCards Municipalities
    # 'ANSONIA': {'type': 'PROPERTYRECORDCARDS', 'towncode': '002'}, # Moved to MapXpress
    'ASHFORD': {'type': 'PROPERTYRECORDCARDS', 'towncode': '003'},
    # 'BETHANY': {'type': 'PROPERTYRECORDCARDS', 'towncode': '008'},
    'BOZRAH': {'type': 'PROPERTYRECORDCARDS', 'towncode': '013'},
    'BRIDGEWATER': {'type': 'PROPERTYRECORDCARDS', 'towncode': '16'},
    'CANAAN': {'type': 'PROPERTYRECORDCARDS', 'towncode': '21'},
    # 'CHESHIRE': {'type': 'PROPERTYRECORDCARDS', 'towncode': '025'},
    'CHESTER': {'type': 'PROPERTYRECORDCARDS', 'towncode': '026'},
    'COLEBROOK': {'type': 'PROPERTYRECORDCARDS', 'towncode': '029'},
    'COLUMBIA': {'type': 'PROPERTYRECORDCARDS', 'towncode': '030'},
    'DANBURY': {'type': 'PROPERTYRECORDCARDS', 'towncode': '034'},
    'DERBY': {'type': 'PROPERTYRECORDCARDS', 'towncode': 'DRB'},
    'DURHAM': {'type': 'PROPERTYRECORDCARDS', 'towncode': '38'},
    'EAST HAMPTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '42'},
    'EAST HAVEN': {'type': 'PROPERTYRECORDCARDS', 'towncode': '044'},
    'EASTFORD': {'type': 'PROPERTYRECORDCARDS', 'towncode': '039'},
    'EASTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '046'},
    'ELLINGTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '048'},
    # 'FARMINGTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '052'},
    'FRANKLIN': {'type': 'PROPERTYRECORDCARDS', 'towncode': '053'},
    'GUILFORD': {'type': 'PROPERTYRECORDCARDS', 'towncode': '060'},
    'HADDAM': {'type': 'PROPERTYRECORDCARDS', 'towncode': '061'},
    'HEBRON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '067'},
    'KILLINGLY': {'type': 'PROPERTYRECORDCARDS', 'towncode': '069'},
    'KILLINGWORTH': {'type': 'PROPERTYRECORDCARDS', 'towncode': '070'},
    'MARLBOROUGH': {'type': 'PROPERTYRECORDCARDS', 'towncode': '079'},
    'MONTVILLE': {'type': 'PROPERTYRECORDCARDS', 'towncode': '086'},
    'NAUGATUCK': {'type': 'PROPERTYRECORDCARDS', 'towncode': '088'},
    'NEW CANAAN': {'type': 'PROPERTYRECORDCARDS', 'towncode': '090'},
    'NEWINGTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '094'},
    'NORFOLK': {'type': 'PROPERTYRECORDCARDS', 'towncode': '098'},
    'NORTH CANAAN': {'type': 'PROPERTYRECORDCARDS', 'towncode': '100'},
    'NORTH HAVEN': {'type': 'PROPERTYRECORDCARDS', 'towncode': '101'},
    'NORTH STONINGTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '102'},
    'OXFORD': {'type': 'PROPERTYRECORDCARDS', 'towncode': '108'},
    'PLAINVILLE': {'type': 'PROPERTYRECORDCARDS', 'towncode': '110'},
    'PLYMOUTH': {'type': 'PROPERTYRECORDCARDS', 'towncode': '111'},
    'PROSPECT': {'type': 'PROPERTYRECORDCARDS', 'towncode': '115'},
    'RIDGEFIELD': {'type': 'PROPERTYRECORDCARDS', 'towncode': '118'},
    'ROCKY HILL': {'type': 'PROPERTYRECORDCARDS', 'towncode': '119'},
    'ROXBURY': {'type': 'PROPERTYRECORDCARDS', 'towncode': '120'},
    'SALISBURY': {'type': 'PROPERTYRECORDCARDS', 'towncode': '122'},
    'SCOTLAND': {'type': 'PROPERTYRECORDCARDS', 'towncode': '123'},
    'SEYMOUR': {'type': 'PROPERTYRECORDCARDS', 'towncode': '124'},
    'SHELTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '126'},
    'SHERMAN': {'type': 'PROPERTYRECORDCARDS', 'towncode': '127', 'path_prefix': '/Sherman'},
    'SIMSBURY': {'type': 'PROPERTYRECORDCARDS', 'towncode': '128'},
    'SUFFIELD': {'type': 'PROPERTYRECORDCARDS', 'towncode': '139'},
    'TORRINGTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '143'},
    'VOLUNTOWN': {'type': 'PROPERTYRECORDCARDS', 'towncode': '147'},
    'WARREN': {'type': 'PROPERTYRECORDCARDS', 'towncode': '149'},
    'WASHINGTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '150'},
    'WATERBURY': {'type': 'PROPERTYRECORDCARDS', 'towncode': '151'},
    'WATERTOWN': {'type': 'PROPERTYRECORDCARDS', 'towncode': '153'},
    'WESTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '157'},
    'WILTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '161'},
    'WINDSOR LOCKS': {'type': 'PROPERTYRECORDCARDS', 'towncode': '165'},
    'WOODBRIDGE': {'type': 'PROPERTYRECORDCARDS', 'towncode': '167'},
    'WOODBURY': {'type': 'PROPERTYRECORDCARDS', 'towncode': '168'},
    'HARTFORD': {'type': 'hartford_script'},
    'STAMFORD': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/stamfordct/'},
    'NORWALK': {'type': 'ct_geodata_csv', 'url': 'https://geodata.ct.gov/api/download/v1/items/82a733423a244c43a9d4bf552954cea9/csv?layers=0', 'town_filter': 'Norwalk'},
    # 'GREENWICH': {'type': 'ct_geodata_csv', 'url': 'https://geodata.ct.gov/api/download/v1/items/82a733423a244c43a9d4bf552954cea9/csv?layers=0', 'town_filter': 'Greenwich'},
    'HAMDEN': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/hamdenct/'},
    'MERIDEN': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/meridenct/'},
    'BRISTOL': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/bristolct/'},
    'WEST HAVEN': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/westhavenct/'},
    'MIDDLETOWN': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/middletownct/'},
    'ENFIELD': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/enfieldct/'},
    'MILFORD': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/milfordct/'},
    'STRATFORD': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/stratfordct/', 'frequency': 'Weekly'},
    # 'EAST HARTFORD': {'type': 'ct_geodata_csv', 'url': 'https://geodata.ct.gov/api/download/v1/items/82a733423a244c43a9d4bf552954cea9/csv?layers=0', 'town_filter': 'East Hartford'},
    'MANCHESTER': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/manchesterct/'},
    'CLINTON': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/clintonct/'},
    'EAST HAMPTON': {'type': 'ct_geodata_csv', 'url': 'https://geodata.ct.gov/api/download/v1/items/82a733423a244c43a9d4bf552954cea9/csv?layers=0', 'town_filter': 'East Hampton'},
    'CROMWELL': {'type': 'ct_geodata_csv', 'url': 'https://geodata.ct.gov/api/download/v1/items/82a733423a244c43a9d4bf552954cea9/csv?layers=0', 'town_filter': 'Cromwell'},
    'OLD LYME': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/oldlymect/'},
    'ESSEX': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/essexct/'},
    'LYME': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/lymect/'},
    'NORWICH': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/norwichct/'},
    # 'GROTON': {'type': 'ct_geodata_csv', 'url': 'https://geodata.ct.gov/api/download/v1/items/82a733423a244c43a9d4bf552954cea9/csv?layers=0', 'town_filter': 'Groton'},
    'SOUTHINGTON': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/southingtonct/'},
    'WALLINGFORD': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/wallingfordct/'},
}

