
# This file contains the configuration for municipal data sources.
# It is shared between the API and the Updater.

MUNICIPAL_DATA_SOURCES = {
    'ANSONIA': {'type': 'MAPXPRESS', 'domain': 'ansonia.mapxpress.net', 'frequency': 'Monthly'},
    'ASHFORD': {'type': 'PROPERTYRECORDCARDS', 'towncode': '003', 'frequency': 'Monthly'},
    'AVON': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/avonct/', 'frequency': 'Weekly'},
    'BEACON FALLS': {'type': 'MAPXPRESS', 'domain': 'beaconfalls.mapxpress.net', 'frequency': 'Monthly'},
    'BERLIN': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/berlinct/', 'frequency': 'Nightly'},
    'BETHANY': {'type': 'MAPXPRESS', 'domain': 'bethany.mapxpress.net', 'frequency': 'Monthly'},
    'BETHLEHEM': {'type': 'MAPXPRESS', 'domain': 'bethlehem.mapxpress.net', 'frequency': 'Monthly'},
    'BLOOMFIELD': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/bloomfieldct/', 'frequency': 'Weekly'},
    'BOZRAH': {'type': 'PROPERTYRECORDCARDS', 'towncode': '013', 'frequency': 'Monthly'},
    'BRIDGEPORT': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/bridgeportct/', 'frequency': 'Nightly'},
    'BRIDGEWATER': {'type': 'PROPERTYRECORDCARDS', 'towncode': '16', 'frequency': 'Monthly'},
    'BRISTOL': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/bristolct/', 'frequency': 'Nightly'},
    'BROOKFIELD': {'type': 'MAPXPRESS', 'domain': 'brookfield.mapxpress.net', 'frequency': 'Monthly'},
    'BURLINGTON': {'type': 'MAPXPRESS', 'domain': 'burlington.mapxpress.net', 'frequency': 'Monthly'},
    'CANAAN': {'type': 'PROPERTYRECORDCARDS', 'towncode': '21', 'frequency': 'Monthly'},
    'CANTON': {'type': 'MAPXPRESS', 'domain': 'canton.mapxpress.net', 'frequency': 'Monthly'},
    'CHESHIRE': {'type': 'MAPXPRESS', 'domain': 'cheshire.mapxpress.net', 'frequency': 'Monthly'},
    'CHESTER': {'type': 'PROPERTYRECORDCARDS', 'towncode': '026', 'frequency': 'Monthly'},
    'CLINTON': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/clintonct/', 'frequency': 'Weekly'},
    'COLCHESTER': {'type': 'MAPXPRESS', 'domain': 'colchester.mapxpress.net', 'frequency': 'Monthly'},
    'COLEBROOK': {'type': 'PROPERTYRECORDCARDS', 'towncode': '029', 'frequency': 'Monthly'},
    'COLUMBIA': {'type': 'PROPERTYRECORDCARDS', 'towncode': '030', 'frequency': 'Monthly'},
    'COVENTRY': {'type': 'MAPXPRESS', 'domain': 'coventry.mapxpress.net', 'frequency': 'Monthly'},
    'CROMWELL': {
        'type': 'MAPGEO',
        'domain': 'cromwellct.mapgeo.io',
        'layout_id': '6032ef5b-8331-4abb-aa9d-e1a114b21443',
        'frequency': 'Monthly'
    },
    'DANBURY': {'type': 'PROPERTYRECORDCARDS', 'towncode': '034', 'frequency': 'Monthly'},
    'DERBY': {'type': 'MAPXPRESS', 'domain': 'derby.mapxpress.net', 'frequency': 'Monthly'},
    'DURHAM': {'type': 'PROPERTYRECORDCARDS', 'towncode': '38', 'frequency': 'Monthly'},
    'EAST HAMPTON': {
        'type': 'TIGHE_BOND',
        'arcgis_find_url': 'https://hostingdata3.tighebond.com/arcgis/rest/services/EastHamptonCT/EastHamptonDynamic/MapServer/find',
        'town_code': '42',
        'frequency': 'Monthly'
    },
    'EAST HARTFORD': {
        'type': 'ct_geodata_csv',
        'url': 'https://geodata.ct.gov/api/download/v1/items/82a733423a244c43a9d4bf552954cea9/csv?layers=0',
        'town_filter': 'EAST HARTFORD',
        'frequency': 'Monthly'
    },
    'EAST HAVEN': {'type': 'MAPXPRESS', 'domain': 'easthaven.mapxpress.net', 'frequency': 'Monthly'},
    'EASTFORD': {'type': 'PROPERTYRECORDCARDS', 'towncode': '039', 'frequency': 'Monthly'},
    'EASTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '046', 'frequency': 'Monthly'},
    'ELLINGTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '048', 'frequency': 'Monthly'},
    'ENFIELD': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/enfieldct/', 'frequency': 'Weekly'},
    'ESSEX': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/essexct/', 'frequency': 'Weekly'},
    'FAIRFIELD': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/fairfieldct/', 'frequency': 'Nightly'},
    'FARMINGTON': {'type': 'MAPXPRESS', 'domain': 'farmington.mapxpress.net', 'frequency': 'Monthly'},
    'FRANKLIN': {'type': 'PROPERTYRECORDCARDS', 'towncode': '053', 'frequency': 'Monthly'},
    'GLASTONBURY': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/glastonburyct/', 'frequency': 'Nightly'},
    'GREENWICH': {
        'type': 'ct_geodata_csv',
        'url': 'https://geodata.ct.gov/api/download/v1/items/82a733423a244c43a9d4bf552954cea9/csv?layers=0',
        'town_filter': 'GREENWICH',
        'frequency': 'Monthly'
    },
    'GROTON': {
        'type': 'ct_geodata_csv',
        'url': 'https://geodata.ct.gov/api/download/v1/items/82a733423a244c43a9d4bf552954cea9/csv?layers=0',
        'town_filter': 'GROTON',
        'frequency': 'Monthly'
    },
    'GUILFORD': {'type': 'MAPXPRESS', 'domain': 'guilford.mapxpress.net', 'id_param': 'parid', 'frequency': 'Monthly'},
    'HADDAM': {'type': 'PROPERTYRECORDCARDS', 'towncode': '061', 'frequency': 'Monthly'},
    'HAMDEN': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/hamdenct/', 'frequency': 'Weekly'},
    'HARTFORD': {'type': 'hartford_enrichment', 'url': 'https://hartfordct.mapgeo.io/', 'frequency': 'Weekly'},
    'HEBRON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '067', 'frequency': 'Monthly'},
    'KILLINGLY': {'type': 'PROPERTYRECORDCARDS', 'towncode': '069', 'frequency': 'Monthly'},
    'KILLINGWORTH': {'type': 'PROPERTYRECORDCARDS', 'towncode': '070', 'frequency': 'Monthly'},
    'LITCHFIELD': {'type': 'MAPXPRESS', 'domain': 'litchfield.mapxpress.net', 'frequency': 'Monthly'},
    'LYME': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/lymect/', 'frequency': 'Weekly'},
    'MANCHESTER': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/manchesterct/', 'frequency': 'Weekly'},
    'MANSFIELD': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/mansfieldct/', 'frequency': 'Weekly'},
    'MARLBOROUGH': {'type': 'PROPERTYRECORDCARDS', 'towncode': '079', 'frequency': 'Monthly'},
    'MERIDEN': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/meridenct/', 'frequency': 'Weekly'},
    'MIDDLEBURY': {'type': 'MAPXPRESS', 'domain': 'middlebury.mapxpress.net', 'frequency': 'Monthly'},
    'MIDDLETOWN': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/middletownct/', 'frequency': 'Weekly'},
    'MILFORD': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/milfordct/', 'frequency': 'Weekly'},
    'MONTVILLE': {'type': 'PROPERTYRECORDCARDS', 'towncode': '086', 'frequency': 'Monthly'},
    'NAUGATUCK': {'type': 'MAPXPRESS', 'domain': 'naugatuck.mapxpress.net', 'frequency': 'Monthly'},
    'NEW BRITAIN': {'type': 'MAPXPRESS', 'domain': 'newbritain.mapxpress.net', 'id_param': 'parid', 'frequency': 'Monthly'},
    'NEW CANAAN': {'type': 'PROPERTYRECORDCARDS', 'towncode': '090', 'frequency': 'Monthly'},
    'NEW HAVEN': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/newhavenct/', 'frequency': 'Weekly'},
    'NEWTOWN': {'type': 'MAPXPRESS', 'domain': 'newtown.mapxpress.net', 'frequency': 'Monthly'},
    'NEWINGTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '094', 'frequency': 'Monthly'},
    'NORFOLK': {'type': 'PROPERTYRECORDCARDS', 'towncode': '098', 'frequency': 'Monthly'},
    'NORTH CANAAN': {'type': 'PROPERTYRECORDCARDS', 'towncode': '100', 'frequency': 'Monthly'},
    'NORTH HAVEN': {'type': 'PROPERTYRECORDCARDS', 'towncode': '101', 'frequency': 'Monthly'},
    'NORTH STONINGTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '102', 'frequency': 'Monthly'},
    'NORWALK': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/norwalkct/', 'frequency': 'Nightly'},
    'NORWICH': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/norwichct/', 'frequency': 'Weekly'},
    'OLD LYME': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/oldlymect/', 'frequency': 'Weekly'},
    'OLD SAYBROOK': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/oldsaybrookct/', 'frequency': 'Weekly'},
    'OXFORD': {'type': 'MAPXPRESS', 'domain': 'oxford.mapxpress.net', 'frequency': 'Monthly'},
    'PLAINVILLE': {'type': 'MAPXPRESS', 'domain': 'plainville.mapxpress.net', 'frequency': 'Monthly'},
    'PLYMOUTH': {'type': 'PROPERTYRECORDCARDS', 'towncode': '111', 'frequency': 'Monthly'},
    'POMFRET': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/pomfretct/', 'frequency': 'Weekly'},
    'PROSPECT': {'type': 'PROPERTYRECORDCARDS', 'towncode': '115', 'frequency': 'Monthly'},
    'RIDGEFIELD': {'type': 'MAPXPRESS', 'domain': 'ridgefield.mapxpress.net', 'frequency': 'Monthly'},
    'ROCKY HILL': {'type': 'PROPERTYRECORDCARDS', 'towncode': '119', 'frequency': 'Monthly'},
    'ROXBURY': {'type': 'PROPERTYRECORDCARDS', 'towncode': '120', 'frequency': 'Monthly'},
    'SALEM': {'type': 'MAPXPRESS', 'domain': 'salem.mapxpress.net', 'frequency': 'Monthly'},
    'SALISBURY': {'type': 'PROPERTYRECORDCARDS', 'towncode': '122', 'frequency': 'Monthly'},
    'SCOTLAND': {'type': 'PROPERTYRECORDCARDS', 'towncode': '123', 'frequency': 'Monthly'},
    'SEYMOUR': {'type': 'MAPXPRESS', 'domain': 'seymour.mapxpress.net', 'frequency': 'Monthly'},
    'SHELTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '126', 'frequency': 'Monthly'},
    'SHERMAN': {'type': 'PROPERTYRECORDCARDS', 'towncode': '127', 'path_prefix': '/Sherman', 'frequency': 'Monthly'},
    'SIMSBURY': {'type': 'PROPERTYRECORDCARDS', 'towncode': '128', 'frequency': 'Monthly'},
    'SOUTHBURY': {'type': 'MAPXPRESS', 'domain': 'southbury.mapxpress.net', 'frequency': 'Monthly'},
    'SOUTHINGTON': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/southingtonct/', 'frequency': 'Weekly'},
    'STAMFORD': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/stamfordct/', 'frequency': 'Weekly'},
    'STONINGTON': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/stoningtonct/', 'frequency': 'Weekly'},
    'STRATFORD': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/stratfordct/', 'frequency': 'Weekly'},
    'SUFFIELD': {'type': 'MAPXPRESS', 'domain': 'suffield.mapxpress.net', 'frequency': 'Monthly'},
    'TORRINGTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '143', 'frequency': 'Monthly'},
    'VERNON': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/vernonct/', 'frequency': 'Weekly'},
    'VOLUNTOWN': {'type': 'PROPERTYRECORDCARDS', 'towncode': '147', 'frequency': 'Monthly'},
    'WALLINGFORD': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/wallingfordct/', 'frequency': 'Weekly'},
    'WARREN': {'type': 'PROPERTYRECORDCARDS', 'towncode': '149', 'frequency': 'Monthly'},
    'WASHINGTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '150', 'frequency': 'Monthly'},
    'WATERBURY': {'type': 'PROPERTYRECORDCARDS', 'towncode': '151', 'frequency': 'Monthly'},
    'WATERTOWN': {'type': 'PROPERTYRECORDCARDS', 'towncode': '153', 'frequency': 'Monthly'},
    'WEST HARTFORD': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/westhartfordct/', 'frequency': 'Weekly'},
    'WEST HAVEN': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/westhavenct/', 'frequency': 'Weekly'},
    'WESTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '157', 'frequency': 'Monthly'},
    'WETHERSFIELD': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/wethersfieldct/', 'frequency': 'Weekly'},
    'WILTON': {'type': 'PROPERTYRECORDCARDS', 'towncode': '161', 'frequency': 'Monthly'},
    'WINDHAM': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/windhamct/', 'frequency': 'Weekly'},
    'WINDSOR': {'type': 'windsor_api', 'url': 'https://windsorct.com', 'frequency': 'Daily'},
    'WINDSOR LOCKS': {'type': 'PROPERTYRECORDCARDS', 'towncode': '165', 'frequency': 'Monthly'},
    'WOLCOTT': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/wolcottct/', 'frequency': 'Weekly'},
    'WOODBRIDGE': {'type': 'PROPERTYRECORDCARDS', 'towncode': '167', 'frequency': 'Monthly'},
    'WOODBURY': {'type': 'PROPERTYRECORDCARDS', 'towncode': '168', 'frequency': 'Monthly'},
    'WOODSTOCK': {'type': 'vision_appraisal', 'url': 'https://gis.vgsi.com/woodstockct/', 'frequency': 'Weekly'},
}
